# Generated by Django 4.0 on 2024-01-17 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0006_news_view_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='view_count',
        ),
    ]
